services:
  app:
    build:
      context: .
      args:
        DISCOGS_PERSONAL_TOKEN: ${DISCOGS_PERSONAL_TOKEN}
        DISCOGS_USERNAME:       ${DISCOGS_USERNAME}
    environment:
      - DISCOGS_PERSONAL_TOKEN
      - DISCOGS_USERNAME
    ports:
      - "3000:3000"
