import type { Metadata } from "next";
import "@/styles/main.scss";
import { Header } from "@/components/Header/Header";
import { AppProvider } from "@/context/AppContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <AppProvider>
      <html lang="en">
        <body className="bg-background-light text-text-light dark:bg-background-dark dark:text-text-dark">
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                let theme = localStorage.getItem('theme') || 
                  (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
                document.documentElement.classList.add(theme);
              })();
            `,
          }}
        />
          <header>
            <Header />
          </header>
          <main className="p-6">
            {children}
          </main>
        </body>
      </html>
    </AppProvider>
  );``
}

export default Layout;
