import type { Metadata } from "next";
import "./globals.css";
import { Header } from "../components/Header/Header";
import { AppProvider } from "@/context/AppContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Layout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <AppProvider>
      <html lang="en">
        <body>
          <header>
            <Header />
          </header>
          <main>
            {children}
          </main>
        </body>
      </html>
    </AppProvider>
  );
}

export default Layout;
